version: "3.3"

services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  api:
    image: cheoljun99/bbot13:1
    ports:
      - 80:8080
    environment:
      DB_PASSWORD: password
      LOG_LVL: debug
      PYTHONUNBUFFERED: 1
    depends_on:
      - mariadb
    command: sh -c "/opt/bbot/start.sh"

volumes:
  bobip-mariadb-data:
